// File generated by scripts/pre-build.js

export const commit = "7279c7a662deb75251ea8bbbbdd78be43cf5fc64";
export const commitShort = "7279c7a";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "Initial boilerplate";
export const commitAt = "2023-05-13T03:05:20.000Z";
export const secondsBetweenCommitAndBuild = 1064.37;
export const minutesBetweenCommitAndBuild = 17.74;
export const timeBetweenCommitAndBuild = "17 minutes and 44 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "1070.42";
export const minutesBetweenCommitAndTestCompletion = "17.84";
export const timeBetweenCommitAndTestCompletion = "17 minutes and 50 seconds";